DECLARE
	VID CUSTOMERS.CUSTOMERID%TYPE;
	VDOB CUSTOMERS.DOB%TYPE;
	VINTEREST LOANS.INTERESTRATE%TYPE;
	VAGE NUMBER;
	CURSOR C_CUST IS SELECT CUSTOMERS.CUSTOMERID,CUSTOMERS.DOB,LOANS.INTERESTRATE FROM CUSTOMERS,LOANS 
	WHERE CUSTOMERS.CUSTOMERID=LOANS.CUSTOMERID;
BEGIN
	OPEN C_CUST;
	LOOP
	FETCH C_CUST INTO VID,VDOB,VINTEREST;
	EXIT WHEN C_CUST%NOTFOUND;
	VAGE:= FLOOR((SYSDATE - VDOB) / 365.25);
	IF VAGE>60 THEN 
		UPDATE LOANS
		SET INTERESTRATE= VINTEREST*0.99
		WHERE LOANS.CUSTOMERID=VID;
	END IF;
	END LOOP;
	CLOSE C_CUST;
	COMMIT;
END;
/