DECLARE
	VID CUSTOMERS.CUSTOMERID%TYPE;
	VBAL CUSTOMERS.BALANCE%TYPE;
	CURSOR C2_CUST IS SELECT CUSTOMERID,BALANCE FROM CUSTOMERS;
BEGIN
	OPEN C2_CUST;
	LOOP
	FETCH C2_CUST INTO VID,VBAL;
	EXIT WHEN C2_CUST%NOTFOUND;
	IF VBAL>10000 THEN 
		UPDATE CUSTOMERS
        SET IsVIP = 'T'
        WHERE CUSTOMERID = VID;
	ELSE
		UPDATE CUSTOMERS
        SET IsVIP = 'F'
        WHERE CUSTOMERID = VID;
	END IF;
	END LOOP;
	CLOSE C2_CUST;
	COMMIT;
END;
/