CREATE OR REPLACE PROCEDURE AddNewCustomer (
    CID IN CUSTOMERS.CUSTOMERID%TYPE,
    CNAME IN CUSTOMERS.NAME%TYPE,
	CDOB IN CUSTOMERS.DOB%TYPE,
	CBAL IN CUSTOMERS.BALANCE%TYPE,
	CLAST IN CUSTOMERS.LASTMODIFIED%TYPE,
	CVIP IN CUSTOMERS.ISVIP%TYPE
) AS

BEGIN
	INSERT INTO Customers VALUES (
	CID, CNAME,CDOB,CBAL,CLAST,CVIP);
    COMMIT;
    

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('SAME CUSTOMER ID ALREADY PRESENT: ' || SQLERRM);
        ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred: ' || SQLERRM);
        ROLLBACK;
END;
/


DECLARE 
	A NUMBER:=&A;
	B VARCHAR2(100):=&B;
	C DATE:=&C;
	D NUMBER:=&D;
	E DATE:=&E;
	F CHAR(1):=&F;
BEGIN
	AddNewCustomer(A,B,C,D,E,F);
END;
/
	