CREATE OR REPLACE PROCEDURE UpdateSalary (
    EID IN EMPLOYEES.EMPLOYEEID%TYPE,
    PER IN NUMBER
) AS
    ESAL EMPLOYEES.SALARY%TYPE;
BEGIN
	SELECT SALARY INTO ESAL
	FROM EMPLOYEES WHERE EMPLOYEEID=EID;
	
    UPDATE EMPLOYEES 
	SET SALARY=ESAL+(ESAL*PER)/100
	WHERE EMPLOYEEID=EID;
        
    COMMIT;
    

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND: ' || SQLERRM);
        ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred: ' || SQLERRM);
        ROLLBACK;
END;
/


DECLARE 
	A NUMBER:=&A;
	B NUMBER:=&B;
BEGIN
	UpdateSalary(A,B);
END;
/
	