CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(GDEPT IN EMPLOYEES.DEPARTMENT%TYPE,PERBON IN NUMBER) AS
BEGIN
	UPDATE EMPLOYEES
	SET SALARY= SALARY+(SALARY* (PERBON/100))
	WHERE DEPARTMENT=GDEPT;
	COMMIT;
END;
/

DECLARE 
	A VARCHAR2(50):=&A;
	B NUMBER:=&B;
BEGIN
	UpdateEmployeeBonus(A,B);
END;
/
	