DECLARE
	A CUSTOMERS.CUSTOMERID%TYPE:=&A;
	C NUMBER;
FUNCTION CalculateAge(CID IN CUSTOMERS.CUSTOMERID%TYPE) RETURN NUMBER IS AGE NUMBER;
BEGIN
	SELECT FLOOR((SYSDATE-DOB)/365.25) INTO AGE FROM CUSTOMERS WHERE CUSTOMERID=11; 
	RETURN AGE;
END;
BEGIN
	C:= CalculateAge(A);
	DBMS_OUTPUT.PUT_LINE('AGE IS '||C);
END;
/