CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
DECLARE
	VBAL ACCOUNTS.BALANCE%TYPE;
	E1 EXCEPTION;
	E2 EXCEPTION;
	E3 EXCEPTION;
BEGIN
	SELECT BALANCE INTO VBAL
	FROM ACCOUNTS WHERE
	ACCOUNTID= :NEW.ACCOUNTID
	FOR UPDATE;
	
	IF :NEW.TRANSACTIONTYPE='WITHDRAWAL' THEN
		IF :NEW.AMOUNT>VBAL THEN
		RAISE E1;
		END IF;
	ELSIF :NEW.TRANSACTIONTYPE='DEPOSIT' THEN
		IF :NEW.AMOUNT<0 THEN
		RAISE E2;
		END IF;
	ELSE
		RAISE E3;
	END IF;
		
	EXCEPTION
		WHEN E1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Withdrawal amount exceeds current balance.');
		WHEN E2 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Deposit amount must be positive.');
		WHEN E3 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Invalid transaction type.');

END;
/