CREATE OR REPLACE TRIGGER LogTransaction
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
	INSERT INTO AUDITLOG VALUES(
	1,:NEW.TRANSACTIONID,:NEW.ACCOUNTID,:NEW.TRANSACTIONDATE,
	:NEW.AMOUNT,:NEW.TRANSACTIONTYPE,SYSDATE);
END;
/


