DECLARE
	AID ACCOUNTS.ACCOUNTID%TYPE;
	ABAL ACCOUNTS.BALANCE%TYPE;
	ANNUAL_FEE NUMBER:=50;
CURSOR ApplyAnnualFee IS SELECT ACCOUNTID,BALANCE FROM ACCOUNTS;
BEGIN
	OPEN ApplyAnnualFee;
	LOOP
	FETCH ApplyAnnualFee INTO AID,ABAL;
	EXIT WHEN ApplyAnnualFee%NOTFOUND;
		UPDATE ACCOUNTS
		SET BALANCE= BALANCE-ANNUAL_FEE
		WHERE ACCOUNTID=AID;
	END LOOP;
	CLOSE ApplyAnnualFee;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('BALANCE UPDATED FOR ALL ACCOUNTS!');
END;
/