DECLARE
	CID ACCOUNTS.CUSTOMERID%TYPE;
	TID TRANSACTIONS.TRANSACTIONID%TYPE;
	AID ACCOUNTS.ACCOUNTID%TYPE;
	TDATE TRANSACTIONS.TRANSACTIONDATE%TYPE;
	TTYPE TRANSACTIONS.TRANSACTIONTYPE%TYPE;
CURSOR GenerateMonthlyStatements IS SELECT ACCOUNTS.CUSTOMERID,TRANSACTIONID,ACCOUNTS.ACCOUNTID,TRANSACTIONDATE,TRANSACTIONTYPE 
FROM TRANSACTIONS,ACCOUNTS WHERE ACCOUNTS.ACCOUNTID=TRANSACTIONS.ACCOUNTID AND EXTRACT(MONTH FROM TRANSACTIONDATE)=EXTRACT(MONTH FROM SYSDATE);
BEGIN
	OPEN GenerateMonthlyStatements;
	LOOP
	FETCH GenerateMonthlyStatements INTO CID,TID,AID,TDATE,TTYPE;
	EXIT WHEN GenerateMonthlyStatements%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE(CID);
	DBMS_OUTPUT.PUT_LINE(TID);
	DBMS_OUTPUT.PUT_LINE(AID);
	DBMS_OUTPUT.PUT_LINE(TDATE);
	DBMS_OUTPUT.PUT_LINE(TTYPE);
	DBMS_OUTPUT.PUT_LINE('-------------------');
	END LOOP;
	CLOSE GenerateMonthlyStatements;
END;
/