DECLARE
	LID LOANS.LOANID%TYPE;
	LIR LOANS.INTERESTRATE%TYPE;
	NEW_IR NUMBER:=5.5;
CURSOR UpdateLoanInterestRates IS SELECT LOANID,INTERESTRATE FROM LOANS;
BEGIN
	OPEN UpdateLoanInterestRates;
	LOOP
	FETCH UpdateLoanInterestRates INTO LID,LIR;
	EXIT WHEN UpdateLoanInterestRates%NOTFOUND;
		UPDATE LOANS
		SET INTERESTRATE= INTERESTRATE+NEW_IR
		WHERE LOANID=LID;
	END LOOP;
	CLOSE UpdateLoanInterestRates;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('INTEREST RATES UPDATED FOR ALL LOANS!');
END;
/