CREATE OR REPLACE PACKAGE CustomerManagement IS
	PROCEDURE ADDCUST(
		CID IN CUSTOMERS.CUSTOMERID%TYPE,
		NAME IN CUSTOMERS.NAME%TYPE,
		DOB IN CUSTOMERS.DOB%TYPE,
		BALANCE IN CUSTOMERS.BALANCE%TYPE,
		LASTMODIFIED IN CUSTOMERS.LASTMODIFIED%TYPE,
		ISVIP IN CUSTOMERS.ISVIP%TYPE);
		
	PROCEDURE UPDATECUST(CID IN CUSTOMERS.CUSTOMERID%TYPE,
		CNAME IN CUSTOMERS.NAME%TYPE);
	
	FUNCTION GETBALANCE(CID IN CUSTOMERS.CUSTOMERID%TYPE) RETURN CUSTOMERS.BALANCE%TYPE;
	
END CustomerManagement;

CREATE OR REPLACE PACKAGE BODY CustomerManagement IS
	PROCEDURE ADDCUST(
		CID IN CUSTOMERS.CUSTOMERID%TYPE,
		NAME IN CUSTOMERS.NAME%TYPE,
		DOB IN CUSTOMERS.DOB%TYPE,
		BALANCE IN CUSTOMERS.BALANCE%TYPE,
		LASTMODIFIED IN CUSTOMERS.LASTMODIFIED%TYPE,
		ISVIP IN CUSTOMERS.ISVIP%TYPE) IS 
		BEGIN
			INSERT INTO CUSTOMERS VALUES(CID,NAME,DOB,BALANCE,LASTMODIFIED,ISVIP);
		END ADDCUST;
		
	PROCEDURE UPDATECUST(CID IN CUSTOMERS.CUSTOMERID%TYPE,
		CNAME IN CUSTOMERS.NAME%TYPE) IS
	BEGIN
		UPDATE CUSTOMERS
		SET NAME=CNAME WHERE 
		CUSTOMERID=CID;
	END UPDATECUST;
	
	
	FUNCTION GETBALANCE(CID IN CUSTOMERS.CUSTOMERID%TYPE) RETURN CUSTOMERS.BALANCE%TYPE 
	IS BAL CUSTOMERS.BALANCE%TYPE;
	BEGIN
		SELECT BALANCE INTO BAL
		FROM CUSTOMERS WHERE
		CUSTOMERID=CID;
		RETURN BAL;
	END GETBALANCE;
	
END CustomerManagement;

DECLARE
	Z NUMBER;
BEGIN
	CustomerManagement.ADDCUST(30,'AUZI','17-FEB-1995',66000,'03-AUG-2024','T');
	CustomerManagement.UPDATECUST(30,'RAUZI');
	Z:=CustomerManagement.GETBALANCE(30);
END;
/
	
