CREATE OR REPLACE PACKAGE EmployeeManagement IS
	PROCEDURE ADDEMP(
		EID IN EMPLOYEES.EMPLOYEEID%TYPE,
		NAME IN EMPLOYEES.NAME%TYPE,
		POSITION IN EMPLOYEES.POSITION%TYPE,
		SALARY IN EMPLOYEES.SALARY%TYPE,
		DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE,
		HIREDATE IN EMPLOYEES.HIREDATE%TYPE);
		
	PROCEDURE UPDATEEMP(EID IN EMPLOYEES.EMPLOYEEID%TYPE,
		ENAME IN EMPLOYEES.NAME%TYPE);
	
	FUNCTION GETANNUALSAL(EID IN EMPLOYEES.EMPLOYEEID%TYPE) RETURN EMPLOYEES.SALARY%TYPE;
	
END EmployeeManagement;

CREATE OR REPLACE PACKAGE BODY EmployeeManagement IS
	PROCEDURE ADDEMP(
		EID IN EMPLOYEES.EMPLOYEEID%TYPE,
		NAME IN EMPLOYEES.NAME%TYPE,
		POSITION IN EMPLOYEES.POSITION%TYPE,
		SALARY IN EMPLOYEES.SALARY%TYPE,
		DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE,
		HIREDATE IN EMPLOYEES.HIREDATE%TYPE) IS 
		BEGIN
			INSERT INTO EMPLOYEES VALUES(EID,NAME,POSITION,SALARY,DEPARTMENT,HIREDATE);
		END ADDEMP;
		
	PROCEDURE UPDATEEMP(EID IN EMPLOYEES.EMPLOYEEID%TYPE,
		ENAME IN EMPLOYEES.NAME%TYPE) IS
	BEGIN
		UPDATE EMPLOYEES
		SET NAME=ENAME WHERE 
		EMPLOYEEID=EID;
	END UPDATEEMP;
	
	
	FUNCTION GETANNUALSAL(EID IN EMPLOYEES.EMPLOYEEID%TYPE) RETURN EMPLOYEES.SALARY%TYPE
	IS SAL EMPLOYEES.SALARY%TYPE;
	BEGIN
		SELECT SALARY INTO SAL
		FROM EMPLOYEES WHERE
		EMPLOYEEID=EID;
		SAL:=SAL*12;
		RETURN SAL;
	END GETANNUALSAL;
	
END EmployeeManagement;


	
